### ISSUE TITLE
panic: assignment to entry in nil map during installation

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#175] opened 2023-07-25 06:22 UTC
RELEEM_MYSQL_MEMORY_LIMIT=0 RELEEM_API_KEY=* RELEEM_MYSQL_ROOT_PASSWORD='' RELEEM_CRON_ENABLE=1 bash -c "$(curl -L https://releem.s3.amazonaws.com/v2/install.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19603  100 19603    0     0  33357      0 --:--:-- --:--:-- --:--:-- 33338

 * Installing dependencies...

 * Downloading Releem Agent, architecture x86_64...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18170  100 18170    0     0  34693      0 --:--:-- --:--:-- --:--:-- 34741
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.5M  100 17.5M    0     0  10.4M      0  0:00:01  0:00:01 --:--:-- 10.4M

 * Configure the application...

 * Detected service name for appling config

 * Configure catalog for copy recommend config

 * The /etc/my.cnf file is used for automatic Releem settings.

 * Adding directive includedir to the MySQL configuration /etc/my.cnf.

 * Configure MySQL user for collect data

 * Using MySQL root user

 Connect to MySQL - successful

 Created new user `releem`

 Connecting to MySQL with user `releem` - successfull

 * Configure mysql memory limit

 * Saving variables to Releem Agent configuration

 - Adding API key to the Releem Agent configuration: /opt/releem/releem.conf
 - Adding Releem Configuration Directory /opt/releem/conf to Releem Agent configuration: /opt/releem/releem.conf
 - Adding user and password mysql to the Releem Agent configuration: /opt/releem/releem.conf
 - Adding MySQL restart command to the Releem Agent configuration: /opt/releem/releem.conf
 - Adding MySQL include directory to the Releem Agent configuration /opt/releem/releem.conf.

 * Configure crontab...

 * Executing Releem Agent for first time...
INFO     : [Main] - 2023/07/25 05:46:37 main.go:82: Starting releem-agent of version is 1.5.0.3
INFO     : [Main] - 2023/07/25 05:46:37 config.go:40: Loading config /opt/releem/releem.conf
INFO     : [Main] - 2023/07/25 05:46:37 main.go:150: InstanceType is Local
INFO     : [Main] - 2023/07/25 05:46:37 main.go:179: Connect Success to DB via tcp 127.0.0.1
INFO     : [Worker] - 2023/07/25 05:46:37 runner.go:71:  * Collecting metrics to recommend a config...
panic: assignment to entry in nil map

goroutine 5 [running]:
http://github.com/Releem/mysqlconfigurer/metrics.MapJoin(...)
        /opt/mysqlconfigurer/metrics/Metrics.go:67
http://github.com/Releem/mysqlconfigurer/metrics.(*DbMetricsGatherer).GetMetrics(0xc0003ce100, 0xc0000bc000)
        /opt/mysqlconfigurer/metrics/dbMetrics.go:107 +0x106d
http://github.com/Releem/mysqlconfigurer/metrics.collectMetrics({0xc0000000a0, 0x6, 0x0?}, {0xda9470, 0xc0003d6d70})
        /opt/mysqlconfigurer/metrics/runner.go:98 +0xf1
http://github.com/Releem/mysqlconfigurer/metrics.RunWorker.func2()
        /opt/mysqlconfigurer/metrics/runner.go:72 +0x1f1
created by http://github.com/Releem/mysqlconfigurer/metrics.RunWorker
        /opt/mysqlconfigurer/metrics/runner.go:69 +0x88c
INFO     : [Main] - 2023/07/25 05:46:43 main.go:82: Starting releem-agent of version is 1.5.0.3
INFO     : [Main] - 2023/07/25 05:46:43 config.go:40: Loading config /opt/releem/releem.conf
INFO     : [Main] - 2023/07/25 05:46:43 main.go:150: InstanceType is Local
INFO     : [Main] - 2023/07/25 05:46:43 main.go:179: Connect Success to DB via tcp 127.0.0.1
INFO     : [Worker] - 2023/07/25 05:46:46 runner.go:47: Exiting

 * Installing and starting Releem Agent service to collect metrics..

 Installing Releem Agent - successful

 Restarting Releem Agent - successful

 * Enabling Performance schema and SlowLog to collect metrics...

 * Performance schema and SlowLog are enabled for metrics collection.

 * Releem Agent is successfully installed.

 * To view Releem recommendations and MySQL metrics, visit https://app.releem.com/dashboard

**Comment by kochetovd** [comment] 2023-08-12 08:49
This problem occurred because there was no Sphinx engine in the information_schema.ENGINES table. The problem is fixed in https://github.com/Releem/mysqlconfigurer/commit/aba0fee5cf084a52ab0d5dc7161a25b10ed2f701

**Closed** 2023-09-30 11:52 UTC
